name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: cd Docker/k8s-backup-mysql && docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/k8s-backup-mysql:$(date +%s) --tag ${{ secrets.DOCKERHUB_USERNAME }}/k8s-backup-mysql:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-backup-mysql --all-tags
